{
 "title": "Edge Beta - Sample dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "t_nodes",
    "label": "Tethered Nodes",
    "query": "label_values(edgetetherednodeid)"
   },
   {
    "name": "app",
    "query": "label_values(edge_micro_service_streams_operator_relativecost{edgetetherednodeid=~'${t_nodes:pipe}'},edgeappname)"
   },
   {
    "name": "ip_ops",
    "label": "Input Port - Operators",
    "query": "label_values(edge_micro_service_streams_operator_ip_tuplesprocessed{edgetetherednodeid=~'${t_nodes:pipe}',edgeappname=~'${app:pipe}'},operatorname)"
   },
   {
    "name": "op_ops",
    "label": "Ouput Port - Operators",
    "query": "label_values(edge_micro_service_streams_operator_op_tuples{edgetetherednodeid=~'${t_nodes:pipe}',edgeappname=~'${app:pipe}'},operatorname)"
   }
  ]
 },
 "panels": [
  { "title": "Panels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Applications",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count (max_over_time(edge_micro_service_streams_operator_ip_tuplesprocessed[$__range])) by (edgeappname, edgetetherednodeid)"
    },
    {
     "expr": "sum(edge_application_cpu_percentage) by (edgeappname, edgetetherednodeid)"
    },
    {
     "expr": "sum(edge_application_memory_percentage) by (edgeappname, edgetetherednodeid)"
    }
   ]
  },
  {
   "title": "Output port rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(edge_micro_service_streams_operator_op_tuples{edgeappname=~'${app:pipe}', edgetetherednodeid=~'${t_nodes:pipe}', operatorname=~'${op_ops}'}[15m])",
     "legendFormat": "{{edgeappname}} - {{operatorname}}"
    }
   ]
  },
  {
   "title": "Operator relative cost ",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "edge_micro_service_streams_operator_relativecost{edgeappname=~'${app:pipe}', edgetetherednodeid=~'${t_nodes:pipe}'}"
    }
   ]
  },
  {
   "title": "Input port rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(edge_micro_service_streams_operator_ip_tuplesprocessed{edgeappname=~'${app:pipe}',edgetetherednodeid=~'${t_nodes:pipe}', operatorname=~'${ip_ops:pipe}'}[15m])",
     "legendFormat": "{{edgeappname}} - {{operatorname}}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU alert",
     "type": "graph",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "edge_application_cpu_percentage"
      }
     ]
    },
    {
     "title": "Memory alert",
     "type": "graph",
     "gridPos": { "h": 4, "w": 8, "x": 7, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "edge_application_memory_percentage"
      }
     ]
    },
    {
     "title": "Tuples dropped alert",
     "type": "graph",
     "gridPos": { "h": 4, "w": 9, "x": 15, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "edge_micro_service_streams_operator_ip_tuplesdropped"
      }
     ]
    }
   ]
  }
 ]
}